" All system-wide defaults are set in $VIMRUNTIME/archlinux.vim (usually just
" /usr/share/vim/vimfiles/archlinux.vim) and sourced by the call to :runtime
" you can find below.  If you wish to change any of those settings, you should
" do it in this file (/etc/vimrc), since archlinux.vim will be overwritten
" everytime an upgrade of the vim packages is performed.  It is recommended to
" make changes after sourcing archlinux.vim since it alters the value of the
" 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages.
runtime! archlinux.vim

" If you prefer the old-style vim functionalty, add 'runtime! vimrc_example.vim'
" Or better yet, read /usr/share/vim/vim72/vimrc_example.vim or the vim manual
" and configure vim to your own liking!

set background=dark
set number
set hls
set hlsearch
set nowrap
set linebreak
set lbr
set mouse=v
set nocursorline
set nocursorcolumn
syntax on
colorscheme neuromouse
if $DISPLAY =~ ":0.0"
    set t_Co=256
endif
set ofu=syntaxcomplete#Complete
set shell=zsh
set ttyfast
set nocompatible
set paste "disable autocomment
"highlight RedundantWhitespace ctermbg=red guibg=red
"match RedundantWhitespace /\s\+$\| \+\ze\t/
" Tabbing
set shiftwidth=4
set tabstop=4
set softtabstop=4
set noexpandtab
" Tabs
imap <C-t> <Esc>:tabnew<CR>
map t :tabnew<CR>:e
map <Tab> :tabn<CR>
map <s-tab> :tabp<CR>
" StatusBar
set laststatus=2
set statusline=[%n]\ %<%f%m%r\ %w\ %y\ \ <%{&fileformat}>%=[%o]\ %l,%c%V\/%L\ \ %P
set showmode
set showcmd
set ruler
set sw=5
" Bindings
"nnoremap j gj
"nnoremap k gk
"nnoremap <Down> gj
"nnoremap <Up> gk
"nnoremap <Home> g<Home>
"nnoremap <End> g<End>

" Filetypes
autocmd BufNewFile,BufRead ~H/rite/mine/* set ft=txt | set wrap | set spell
autocmd BufNewFile,BufRead ~H/mail/*  set ft=mail | set textwidth=72 | set spell
autocmd BufNewFile,BufRead Xdefaults  set ft=xdefaults
autocmd BufNewFile,BufRead .stumpwmrc set ft=lisp
autocmd BufNewFile,BufRead ~/stumpwm/storage/* set ft=lisp
autocmd BufNewFile,BufRead ~/zsh/*    set ft=zsh
autocmd BufNewFile,BufRead .TODO_*    set ft=conf
autocmd FileType html,xml,xsl set spell
autocmd FileType c      set formatoptions+=ro
autocmd FileType make   set noexpandtab shiftwidth=8
autocmd FileType python set expandtab shiftwidth=2 tabstop=2
autocmd FileType c      syn match matchName /\(#define\)\@<= .*/

" Workarrounds
autocmd BufWinLeave * call clearmatches() " Fix progressive memory leak on match when switching buffers
