#!/bin/sh
#
# ~/.xinitrc

# Source files
/usr/bin/xrdb -load ~/.config/xorg/Xdefaults
source ~/.config/shell/exports

# Start deamons
/usr/bin/mpd ~/.mpd/mpd.conf
/usr/bin/urxvtd -q -f -o

# Special keys
#/usr/bin/xmodmap -e "keycode 173 = XF86AudioPrev"
#/usr/bin/xmodmap -e "keycode 172 = XF86AudioPlay"
#/usr/bin/xmodmap -e "keycode 171 = XF86AudioNext"
#/usr/bin/xmodmap -e "keycode 174 = XF86AudioStop"
#/usr/bin/xmodmap -e "keycode 121 = XF86AudioMute"
#/usr/bin/xmodmap -e "keycode 122 = XF86AudioLowerVolume"
#/usr/bin/xmodmap -e "keycode 123 = XF86AudioRaiseVolume"
#/usr/bin/xmodmap -e "keycode 199 = XF86TouchpadToggle"
#/usr/bin/xmodmap -e "keycode 232 = XF86MonBrightnessDown"
#/usr/bin/xmodmap -e "keycode 233 = XF86MonBrightnessUp"

# Set typematic
/usr/bin/xset r rate 180 20


# Set wallpaper
#/usr/bin/feh --bg-scale ~/Pictures/wallpapers/Molly.png
/usr/bin/feh --bg-scale ~/Pictures/wallpapers/tessier-ashpool.png

#Automounting
/usr/bin/udiskie &

# Launch window manager
exec dbus-launch --sh-syntax --exit-with-session /usr/bin/xmonad
